//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public long Id { get; set; }
        public string name { get; set; }
        public int IdPerson { get; set; }
        public int IdCountry { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Country Country { get; set; }
    }
}
