//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public class Gender
    {
   
        public Gender()
        {
            Person = new HashSet<Person>();
        }
    
        public int GenderId { get; set; }
        public string Description { get; set; }
        public virtual ICollection<Person> Person { get; set; }
    }
}
